config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :jobs
  root 'jobs#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user_signed_in?
        can :manage, :all
    end
  end
end

app/models/job.rb
class Job < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :title, :company, :salary, :description, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :user_name, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs, dependent: :destroy


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
  	redirect_to root_path, :alert => exception.message
  end

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :full_name
  	devise_parameter_sanitizer.for(:account_update) << :full_name
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all.order('created_at DESC').page params[:page]
  end
  
  # GET /jobs/1
  # GET /jobs/1.json
  def show
    authorize! :read, @job
  end

  # GET /jobs/new
  def new
    @job = current_user.jobs.build
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_user.jobs.build(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :company, :description, :salary, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= simple_form_for(@job, html: {class: 'form-horizontal'}) do |f|
  = f.input :title, label: 'Job Title', input_html: {class: 'form-control'}
  = f.input :company, label: 'Your Company', input_html: {class: 'form-control'}
  /= f.input :description, label: 'Job Description', input_html: {class: 'form-control'}
  = f.input :salary, input_html: {class: 'form-control'}
  = f.input :description, as: :bootsy, label: 'Job Description', input_html: {class: 'form-control'}
  %br/
  .form-group
    = f.button :submit

app/views/jobs/edit.html.haml
%h1 Editing Job

= render 'form'

= link_to 'Back', root_path

app/views/jobs/index.html.haml
#jobs
  - @jobs.each do |job|
    .job
      %h2= link_to job.title, job
      %p= job.company
      %p
        Salary:  
        =job.salary
        $
      / %p #{raw(job.description[0..200] + '...')}
      %p #{ActionView::Base.full_sanitizer.sanitize(job.description)[0..200] + "..."}
#paginator.text-center
  = paginate @jobs

app/views/jobs/new.html.haml
%h1 New Job

= render 'form'

= link_to 'Back', root_path

app/views/jobs/show.html.haml
#jobs
	.job
		%h1= @job.title
		%p= @job.company
		%p
			%strong Salary:
			= @job.salary
			$
		%button.btn.btn-default= link_to 'Apply for job', ''
		%p= raw(@job.description)
		%button.btn.btn-default= link_to 'Apply for job', ''
#links
	- if @job.user == current_user
		= link_to 'Back', root_path, class: 'btn btn-sm btn-default'
		= link_to 'Edit', edit_job_path(@job), class: 'btn btn-sm btn-default'
		= link_to 'Delete', job_path(@job), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-default'

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Jobs Board
		= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
		= javascript_include_tag 'application', 'data-turbolinks-track' => true
		= csrf_meta_tags
	%body
		%nav.navbar.navbar-inverse
			.container
				.navbar-brand
					= link_to 'Jobs Board', root_path
				%ul.nav.navbar-nav.navbar-right
					- if user_signed_in?
						%li= link_to 'New Job', new_job_path
						%li= link_to current_user.full_name, edit_user_registration_path
						%li= link_to 'Sign out', destroy_user_session_path, method: :delete
					- else
						%li= link_to 'Sign in', new_user_session_path
						%li= link_to 'Create new account', new_user_registration_path
		.container
			.col-md-8.col-md-offset-2
				- flash.each do |name, msg|
					= content_tag :div, msg, class: 'alert alert-info'
				= yield
		%footer.bs-docs-footer
			.container
				%ul.bs-docs-footer-links
					%li= link_to 'GitHub', '#'
					%li= link_to 'Twitter', '#'
					%li= link_to 'Facebook', '#'
					%li= link_to 'Linkedln', '#'
					%li= link_to 'Google+', '#'
				%p
					Designed and built with all the love in the world by
					%a{:href => "https://twitter.com/mdo", :target => '_blank'} @mdo
					and 
					%a{:href => "https://twitter.com/fat", :target => '@fat'}
					\. Maintained by the
					%a{:href => "https://github.com/orgs/twbs/people"} core team
					with the help of
					%a{:href => "https://github.com/twbs/bootstrap/graphs/contributors"} our contributors
					\.
				%p
					Code licensed
					%a{:href => "https://github.com/twbs/bootstrap/blob/master/LICENSE", :target => '_blank', :rel => 'license'} MIT
					, docs
					%a{:href => "https://creativecommons.org/licenses/by/3.0/", :target => '_blank', :rel => 'license'} CC BY 3.0
					\.